# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/joshbirnholz/JBPodSpecs.git'

target 'chaintune' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for chaintune
  pod 'Firebase/Auth'
  pod 'Firebase'
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'GoogleSignIn'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'JBCalendarDatePicker'




  target 'chaintuneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'chaintuneUITests' do
    # Pods for testing
  end

end
